env: "local" # dev, prod
dsn: "postgres://postgres:postgres@localhost:54321/lib_isod"
watcher_create: "create"
watcher_recovery: "recovery"
#token_ttl: 1h
grpc:
  port: 44045
  timeout: 10h
http:
  host: "127.0.0.1"
  port: "8080"